name: Psychtoolbox-3
url: http://psychtoolbox.org
permalink: pretty
pygments: false
markdown: kramdown

gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: :as_char
  toc_levels: 1..5
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

google_analytics:
  account: UA-6031251-4
